on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm Install
      run: |
        npm install
    - name: Staging Build
      run: |
        npm build
    - name: Unit Tests
      run: |
        npm test
    - name: Deploy to S3
      uses: KareemSalem7/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
